# Generated by Django 2.2 on 2019-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0024_auto_20190328_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('img', models.ImageField(default='default.png', upload_to='')),
                ('description', models.TextField(default='defaultText')),
            ],
        ),
    ]
