# Generated by Django 2.2 on 2019-05-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0025_theme_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cne', models.CharField(max_length=10)),
                ('theme', models.CharField(choices=[('Dance', 'dance'), ('Music', 'music'), ('Theatre', 'theatre'), ('Dessin', 'dessin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='activ_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PE.Adherent')),
            ],
        ),
    ]
