# Generated by Django 2.2 on 2019-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0026_activ_art_adherent'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatpfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sujet', models.CharField(max_length=200)),
                ('filiere', models.CharField(choices=[('Dance', 'dance'), ('Music', 'music'), ('Theatre', 'theatre'), ('Dessin', 'dessin')], max_length=100)),
                ('nom_ancadrant', models.CharField(max_length=30)),
                ('rapport_pfe', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='adherent',
            name='theme',
            field=models.CharField(choices=[('Dance', 'dance'), ('Music', 'music'), ('Theatre', 'theatre'), ('Dessin', 'dessin')], max_length=100),
        ),
    ]
