# Generated by Django 2.2 on 2019-05-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0028_auto_20190520_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatpfe',
            name='filiere',
            field=models.CharField(max_length=100),
        ),
    ]
