# Generated by Django 2.2 on 2019-05-21 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0030_auto_20190521_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatpfe',
            name='cne',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
