# Generated by Django 2.2 on 2019-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0031_candidatpfe_cne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etu_estchalleng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cne', models.CharField(max_length=30)),
                ('sujet', models.CharField(max_length=200)),
                ('filiere', models.CharField(choices=[('DUT-FC2', 'DUT-FC2'), ('DUT-GE2-EEI', 'DUT-GE2-EEI'), ('DUT-GE2-EII', 'DUT-GE2-EII'), ('DUT-GE2-RLI', 'DUT-GE2-RLI'), ('DUT-GEA2', 'DUT-GEA2'), ('DUT-GI2', 'DUT-GI2'), ('DUT-GM2', 'DUT-GM2'), ('DUT-TC2', 'DUT-TC2'), ('DUT-GP2', 'DUT-GP2')], max_length=100)),
                ('nom_ancadrant', models.CharField(max_length=30)),
                ('rapport_pfe', models.FileField(upload_to='')),
            ],
        ),
    ]
