# Generated by Django 2.2 on 2019-05-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0032_etu_estchalleng'),
    ]

    operations = [
        migrations.CreateModel(
            name='concourpfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PE.Etu_estchalleng')),
            ],
        ),
    ]
