# Generated by Django 2.2 on 2019-05-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0033_concourpfe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidatpfe',
        ),
    ]
