# Generated by Django 2.2 on 2019-05-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0035_pfes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pfes',
            new_name='Pfe',
        ),
    ]
