# Generated by Django 2.2 on 2019-05-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0036_auto_20190527_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='sujet',
            field=models.CharField(max_length=99),
        ),
    ]
