# Generated by Django 2.2 on 2019-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0037_auto_20190527_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laurea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('filiere', models.CharField(choices=[('DUT-FC2', 'DUT-FC2'), ('DUT-GE2-EEI', 'DUT-GE2-EEI'), ('DUT-GE2-EII', 'DUT-GE2-EII'), ('DUT-GE2-RLI', 'DUT-GE2-RLI'), ('DUT-GEA2', 'DUT-GEA2'), ('DUT-GI2', 'DUT-GI2'), ('DUT-GM2', 'DUT-GM2'), ('DUT-TC2', 'DUT-TC2'), ('DUT-GP2', 'DUT-GP2')], max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('annee_d_diplome', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('telefone', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=20)),
                ('paye', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('etablissement', models.CharField(default='Null', max_length=100)),
                ('Societe', models.CharField(default='Null', max_length=100)),
                ('poste', models.CharField(default='null', max_length=100)),
                ('filiere_actual', models.CharField(max_length=100)),
            ],
        ),
    ]
