# Generated by Django 2.2 on 2019-05-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0038_laurea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laurea',
            name='image',
        ),
    ]
