# Generated by Django 2.2 on 2019-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0042_auto_20190531_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laurea',
            name='image',
            field=models.ImageField(upload_to='arts/'),
        ),
    ]
