# Generated by Django 2.2 on 2019-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0046_auto_20190531_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laurea',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
